services:
  chat-ui:
    image: {{ACCOUNT_ID}}.dkr.ecr.{{REGION}}.amazonaws.com/chat-ui-repo:latest
    environment:
      CPU_CORES: "max"
    ports:
      - "80:3000"
    depends_on:
      - mongo_db
      - llm_model

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"

  llm_model:
    image: vllm/vllm-openai
    environment:
      HF_TOKEN: "${HF_TOKEN}"
    command: "--host 0.0.0.0 --model ${LLM_MODEL}"
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all
networks:
  default:
    driver: bridge