version: '3.8'

services:
  chat-ui:
    image: {{ACCOUNT_ID}}.dkr.ecr.{{REGION}}.amazonaws.com/chat-ui-repo:latest
    environment:
      CPU_CORES: "max"
    ports:
      - "80:3000"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge